config/routes.rb
Sapo::Application.routes.draw do
  resources :players

  resources :teams

  resources :games

  root 'games#home'
  get "/teams/new/:id", controller:"teams",action: :new
  get "/players/new/:id", controller:"players",action: :new
  get "/play/:id", controller:"games",action: :play, as: :play
  get "/winner/:id",controller:"games",action: :winner, as: :winner
  post "/add_points/:id", controller:"games",action: :add_points, as: :add_points
  get "/restart/:id", controller:"games",action: :restart, as: :restart
  get "/top_players", controller:"players",action: :top_players, as: :top_players
  get "/top_teams", controller:"teams",action: :top_teams, as: :top_teams
  get "/top_games", controller:"games",action: :top_games, as: :top_games
  get "/how_to", controller:"information",action: :how_to, as: :how_to
  get "/what",controller:"information",action: :what, as: :what
  post "/undo/:id", controller:"games",action: :undo, as: :undo

  

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :teams

#Methods that grabs fields from the model
  #getters
  def scoreLimit
    self.score_limit
  end

  def gameName
    self.game_name
  end

  def numberOfPlayers
    self.number_of_players
  end

  def numberOfTeams
  	self.teams.size
  end

  def winnerTeam
		Team.find_by_id(self.winner_team)
  end

  def getTeam
    self.teams[self.teamTurn]
  end

  
  def getTeamsInScoreOrder
    self.teams.order(total_score: :desc)
  end

  def getPlayer
    self.teams[self.teamTurn].players[self.playerTurn]
  end

  def playerTurn
    self.player_turn
  end

  def teamTurn
    self.team_turn
  end
  #end getters

  #setters
  def setScoreLimit(limit)
    if limit > 0
      self.score_limit = limit
    	self.save
    end
  end

  def setGameName(name)
    if name.present?
      self.game_name = name
      self.save
    end
  end

  def setNumberOfPlayers(number)
    if number > 0
      self.number_of_players = number
      self.save
    end
  end

  def setWinnerTeam(teamId)

    if Team.find_by_id(teamId).present?
      self.winner_team = teamId
      self.save
    end
  end
  #end setters
  
  def setPlayerTurn(number)
    self.player_turn = number
    self.save
  end

  def setTeamTurn(number)
    self.team_turn = number
    self.save
  end
  
  def nextPlayer
    self.player_turn += 1
    self.save
    self.reload
    
    if self.player_turn == self.numberOfPlayers
      self.player_turn = 0
      self.save
    end
  end

  def nextTeam
    self.team_turn += 1
    self.save
    self.reload
    
    if self.team_turn == self.numberOfTeams
      self.team_turn = 0
      self.save
      self.nextPlayer
    end
  end

  def prevPlayer

    #then we go back to the last team and change the player index
    if self.teamTurn == 0
      prevTeam = self.numberOfTeams - 1
      
      #if we are looking at the first player in the set
      if self.playerTurn == 0
        #choose last player of previous set
        prevPlayer = self.numberOfPlayers - 1
      else
        #choose the previous player within this set
        prevPlayer = self.playerTurn - 1
      end
    #else just got to the last team
    else
      prevTeam = self.teamTurn - 1
      prevPlayer = self.playerTurn
    end

    self.setTeamTurn(prevTeam)
    self.setPlayerTurn(prevPlayer)
    
    self.teams[prevTeam].players[prevPlayer]
  end


  def clearTeamScore
    self.teams.each do |team|
      team.clearPlayersScore
    end
    self.save
    
  end

  def teamsReady
    if self.numberOfTeams > 1
      self.teams.each do |team|
        if team.teamSize != self.numberOfPlayers
          return false
        end
      end
    else
      return false
    end
    return true
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  #changes must be done
  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  def home
  end
  
  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)
    @game.setWinnerTeam(nil)
    @game.setPlayerTurn(0)
    @game.setTeamTurn(0)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render action: 'show', status: :created, location: @game }
      else
        format.html { render action: 'new' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to '/' }
      format.json { head :no_content }
    end
  end

  def play
    @game = Game.find_by_id(params[:id])
  end

  def add_points
    @game = Game.find_by_id(params[:id])
    player = @game.getPlayer
    points_scored = params[:points].to_i
    
    player.add_to_score(points_scored)
    player.set_prev_throw(points_scored)
    
    if @game.save
      @game.reload
      if @game.getTeam.totalScore >= @game.score_limit
        @game.setWinnerTeam(@game.getTeam.id)
        redirect_to action: :winner
      else
        @game.nextTeam
        redirect_to action: :play
      end

    else
      format.html {render play_game_path}
      format.json { render json: @game.errors, status: :unprocessable_entity}
    end
  end

  def undo
    @game = Game.find_by_id(params[:id])
    player = @game.prevPlayer

    if player.prev_throw.present?
      player.reduce_from_score(player.prev_throw)
    end

    player.set_prev_throw(nil)
    redirect_to action: :play

  end

  def winner
    @game = Game.find_by_id(params[:id])
    @winner = @game.winnerTeam
  end

  def restart
    @game = Game.find_by_id(params[:id])
    
    @game.setTeamTurn(0)
    @game.setPlayerTurn(0)
    @game.setWinnerTeam(nil)
    @game.clearTeamScore

    redirect_to action: :play
  end

  def top_games
    @games = Game.all.order(score_limit: :desc).limit(20)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:game_name, :score_limit, :number_of_players, :winner_team)
    end

end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :game_name %><br>
    <%= f.text_field :game_name %>
  </div>
  <div class="field">
    <%= f.label :score_limit %><br>
    <%= f.number_field :score_limit %>
  </div>
  <div class="field">
    <%= f.label :number_of_players %><br>
    <%= f.number_field :number_of_players %>
  </div>

  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/_form_addScore.html.erb
<%= form_tag("/add_points/#{@game.id}", method:"post") do %>
	<%= label_tag(:points,"Points Scored:") %>
	<%= number_field_tag(:points) %>
	<div class= "clearfix"></div>
	<%= submit_tag("Add Points") %>
<% end %>

app/views/games/_form_undo.html.erb
<%= form_tag("/undo/#{@game.id}", method:"post") do %>
	<%= submit_tag("Undo") %>
<% end %>

app/views/games/_game_details.html.erb
<!---Show Game Details-->
<p>
	<strong>Game name:</strong>
  <%= @game.gameName %>
</p>

<p>
  <strong>Score limit:</strong>
  <%= @game.scoreLimit %> pts
</p>

<p>
  <strong>Number of players on each Team:</strong>
  <%= @game.numberOfPlayers %> 
</p>

<!-- IF a Winner is present we show that there is a winner -->
<% if @game.winnerTeam.present? %>
	<p>
	  <strong>Winning team:</strong>
	  <%= @game.winnerTeam.teamName %>
	</p>
<% else %>

<%= link_to 'Edit', edit_game_path %> |
<%= link_to "Delete", @game, method: :delete, data:{ confirm: "Are you sure? This will DELETE all of the teams' records"}  %>
<%end %>
<!--< link_to 'Back', games_path >-->
<!--End Game Details-->
<hr/>

app/views/games/_team_details.html.erb
<!--Team Linked To this Game-->

<h3>Teams</h3>

<!--If there are no teams for the game we send out a warning-->
<% if @game.teams.empty? %>
	<div class ="alert">
		<p><strong>Warning:</strong> 
			There are currently no teams ready to play
		</p>
	</div>
<% else %>
	
	<!-- If there is only one team a warning notice appears -->
	<% if @game.numberOfTeams == 1 %>
		<div class ="alert">
			<p><strong>Warning:</strong> 
				You must add at least one more team to play
			</p>
		</div>	
	<% end %>


<!--For each team associated with this game
	Present the team name and the team score-->

	<% @game.teams.each	do |team| %>
		
		<p>
			<strong>Team:</strong>
			<%= team.teamName %>
		</p>

		<p>
			<strong>Total Score:</strong>
			<%= team.totalScore %>
		</p>

		<!--If the team is low on players it displays a notice-->
		<% if team.teamSize < @game.numberOfPlayers %>
			<div class ="alert">
				<p><strong>Warning:</strong> 
				Number Of Players That Must Be Added: <%= @game.numberOfPlayers - team.teamSize %>
				</p>
			</div>
		<% end %>

		<!--If the team is over-->
		<% if team.teamSize > @game.numberOfPlayers %>
			<div class ="alert">
				<p><strong>Warning:</strong> 
				Number Of Players That Must Be Removed: <%= team.teamSize - @game.numberOfPlayers %>
				</p>
			</div>
		<% end %>


		<% unless @game.winnerTeam.present? %>
			<%= link_to 'Roster', team_path(team)  %> |
			<%= link_to 'Edit Team', edit_team_path(team) %> |
			<%= link_to 'Remove Team', team, method: :delete, data: { confirm: 'Are you sure?' } %>
		<%end%>
		
		<hr />
	<% end %>

<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>


<%= link_to 'Back', @game %>

app/views/games/home.html.erb
<div class = "hero-unit">
	<h1>Manage Your Sapo Game</h1>
	
	<div class ="linkTo">
		<%=link_to (new_game_path) do %>
			<div class="btn btn-inverse">
				<span>New Game</span>
			</div>
		<% end %>
	</div>
</div>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table>
  <thead>
    <tr>
      <th>Game name|</th>
      <th>Score limit|</th>
      <th>Number of players|</th>
      <th>Winner team|</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.game_name %></td>
        <td><%= game.score_limit %></td>
        <td><%= game.number_of_players %></td>
        <td><%= game.winner_team %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<div id="newView">
	<h1>New Game</h1>

	<%= render 'form' %>

	<%= link_to '/' do %>
		<div class = "btn">
			<span>Back</span>
		</div>
	<% end %>
</div>

app/views/games/play.html.erb
<h1><%= @game.gameName %></h1>
<div class="row-fluid">
	<div id="scoreBoard">
		<h3>Score Board</h3>
			
		<p><strong>Team</strong></p>
		<p class = "points"><strong>Points</strong></p>
		<div class="clearfix"></div>

			<% @game.getTeamsInScoreOrder.each do |team|%>
				<p><strong><%="#{team.teamName}:"%></strong></p>
				<p class="points"><%="#{team.totalScore}pts"%></p>
				<div class="clearfix"></div>	
			<% end %>
	</div>
	
	<div id ="upToBat">
		<h3><%= "#{@game.getTeam.teamName}"%></h3>
		<h4><%="Throwing: #{@game.getPlayer.playerName}"%></h4>
		<p>Points to Win: <%=@game.scoreLimit-@game.getTeam.totalScore%>pts</p>
		
		<%= render 'form_addScore' %>
		<%= render 'form_undo' %>
	</div>
</div>

app/views/games/show.html.erb
<!--<p id="notice"><%= notice %></p>-->


<h1>Game Setup</h1>


<%= render 'game_details' %>
<%= render 'team_details' %>


<% if !@game.winnerTeam.present? %>
	<%= link_to 'Add Team', "#{new_team_path}/#{@game.id}"%>
	<% if @game.teamsReady %>
	| <%= link_to 'Start Game', "/play/#{@game.id}" %>
	<% end %>
<% end %>

app/views/games/top_games.html.erb
<h1>Top Scoring Games</h1>
<ol>
<% @games.each do |game|%>	
		<% unless !game.winnerTeam.present?%>	
			<li>
				<ul>
					<li>
						<%= link_to(game) do %>
							<%=game.gameName%>
						<%end%>
					</li>

					<li>Score Limit <%=game.score_limit%> pts</li>
					<li>Game Won With: 
						<%= link_to (game.winnerTeam) do %>
							<%= game.winnerTeam.total_score %> pts	
						<% end %>
					</li>
				</ul>
			</li>
		<% end %>
		<hr/>

<% end %>
</ol>

app/views/games/winner.html.erb
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

<div class = "hero-unit">
	<h1><%=@winner.teamName%> Wins!</h1>
</div>

<p>
	Congratulations You have just beat your friends at a game of Sapo! See your team's  contributions to the game below.
</p>


<a href="https://twitter.com/share" class="twitter-share-button" data-lang="en" data-count="none" data-hashtags="Sapo,MarcandoSapo,Sapogamemanager,Latino" data-url="test.com" data-related="Jim_Bedrock02" data-text="I just played a game of Sapo using the Sapo Game Manager!">Tweet</a>

<h3>Team Stats</h3>

<ol>
<% @winner.getPlayersInOrder.each do |players|%>
	<li><strong><%= players.playerName%></strong>:<%= players.score %></li>
<%end%>
</ol>