config/routes.rb
Sapo::Application.routes.draw do
  resources :players

  resources :teams

  resources :games

  root 'games#home'
  get "/teams/new/:id", controller:"teams",action: :new
  get "/players/new/:id", controller:"players",action: :new
  get "/play/:id", controller:"games",action: :play, as: :play
  get "/winner/:id",controller:"games",action: :winner, as: :winner
  post "/add_points/:id", controller:"games",action: :add_points, as: :add_points
  get "/restart/:id", controller:"games",action: :restart, as: :restart
  get "/top_players", controller:"players",action: :top_players, as: :top_players
  get "/top_teams", controller:"teams",action: :top_teams, as: :top_teams
  get "/top_games", controller:"games",action: :top_games, as: :top_games
  get "/how_to", controller:"information",action: :how_to, as: :how_to
  get "/what",controller:"information",action: :what, as: :what
  post "/undo/:id", controller:"games",action: :undo, as: :undo

  

end

app/models/player.rb
class Player < ActiveRecord::Base
	belongs_to :team
	after_save :updateMyTeam, only: [:addToScore,:reduceFromScore]

	#getters

	def playerName
		self.player_name
	end

	def pointsScored
		self.score
	end

	def prev_throw
		self.previous_throw
	end

	def set_prev_throw(number)
		self.previous_throw = number
		self.save
	end

	def add_to_score(number)
		self.score += number
		self.save
	end

	def reduce_from_score(number)
		self.score -= number
		self.save
	end

	def getTeam
		self.team
	end

	def updateMyTeam
		if self.team.present?
			self.team.updateTotalScore
		end
	end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
     
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)
    @player.score = 0

    #assign turn number based on how many players are present
    @team = Team.find_by_id(params[:team_id])
    #@player.turn_number = @team.players.size

    respond_to do |format|
      if @player.save
        #add player to the team
        @team.players << @player

        format.html { redirect_to @player.team, notice: 'Player was successfully created.' }
        format.json { render action: 'show', status: :created, location: @player }
      else
        format.html { render action: 'new' }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  def top_players
    @players = Player.all().order(score: :desc).limit(20)
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @team = @player.team
    @player.destroy
    respond_to do |format|
      format.html { redirect_to team_path(@team) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:player_name, :score, :turn_number)
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :player_name %><br>
    <%= f.text_field :player_name %>
  </div>
  
  <!-- Pass in the game id if it is present-->
  <% if @team.present? %>
    <%= hidden_field_tag :team_id, @team.id %>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', team_path(@player.team) %>

app/views/players/index.html.erb
<h1>Listing players</h1>

<table>
  <thead>
    <tr>
      <th>Player name</th>
      <th>Score</th>
      <th>Turn number</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.player_name %></td>
        <td><%= player.score %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<div class ="newView">
	<h1>New player</h1>
	<% @team = Team.find_by_id(params[:id]) %>
	<%= render 'form' %>

	<%= link_to 'Back To Team', team_path(@team) %>
</div>

app/views/players/show.html.erb
<!--<p id="notice"><%= notice %></p>-->

<p>
  <strong>Player name:</strong>
  <%= @player.player_name %>
</p>

<p>
  <strong>Score:</strong>
  <%= @player.score %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', team_path(@player.team) %>

app/views/players/top_players.html.erb
<h1>Top Scoring Players</h1>
<ol>
<% @players.each do |player|%>
	<% unless !player.getTeam.present? ||  !player.getTeam.getGame.present? %>
		<% unless !player.getTeam.getGame.winnerTeam.present? %>
			<li>
				<ul>
					
					<li>
						<%= link_to(player) do %>
							<%=player.playerName%>
						<%end%>
					</li>

					<li>Scored <%=player.pointsScored%>pts</li>
					
					<li>On Team: 
						<%= link_to(player.getTeam) do %>
							<%=player.getTeam.teamName%>
						<% end %>
					</li>
					
					<li>In Game:
						<%= link_to(player.getTeam.getGame) do %>
							<%=player.getTeam.getGame.gameName%>
						<%end%>
					</li>
				</ul>
			</li>
			<hr/>
		<% end %>
	<%end%>
<% end %>
</ol>